# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install pre-reqs
      run: sudo apt install -y build-essential autoconf bison flex texinfo help2man gawk libtool libncurses5-dev python3-dev python3-distutils git libtool-bin

    - name: Build ct-ng
      run: |
        mkdir -p build
        pwd
        git clone --depth 1 https://github.com/crosstool-ng/crosstool-ng.git
        cd crosstool-ng
        ./bootstrap
        ./configure --prefix=/opt/crosstool-ng
        make
        sudo make install
        cd /opt
        tar czf $HOME/ct-ng-tools.tgz crosstool-ng

    - name: Archive ct-ng tools
      uses: actions/upload-artifact@v1
      with:
        name: crosstool-ng-tools
        path: ct-ng-tools.tgz

    - name: Build x-tools
      run: |
        mkdir -p $HOME/ct-build
        cd $HOME/ct-build
        cp $GITHUB_WORKSPACE/crosstool-ng.config ./.config
        /opt/crosstool-ng/bin/ct-ng --quiet build
        cd /opt
        tar czf $HOME/x-tools.tgz x-tools

    - name: Archive x-tools
      uses: actions/upload-artifact@v1
      with:
        name: x-tools
        path: x-tools.tgz
        
